### PR TITLE
Feature highlights and annotations in IDE

### PR DESCRIPTION
**Pull request by frextrite**
highlighting and annotating inside the IDE is implemented

### CODE REVIEW

**Comment by frextrite** [comment]
Travis builds failing for OpenJDK 11. Reported https://travis-ci.community/t/maven-received-status-code-403-from-server-forbidden/4641

**Comment by ksdme** [comment]
30 Commits are unacceptable in a single PR.

**Comment by ksdme** [comment]
Please clean it up and also ensure we have high test coverage (>75%).

**Comment by frextrite** [comment]
I agree 30 commits are a lot. I could squash a few beginning commits into a single commit, but all of the commits are relevant imo. At this stage, I had all of the components created and it's all about integrating them with each-other. I could've gone with one class/PR but that would've just taken longer to code (and make sure everything works) and to get it out.

As far as the code goes, I've re-iterated multiple times to refactor+optimize it and I believe there would be no (a few maybe?) complaints regarding the code.

**Comment by frextrite** [comment]
Split into multiple-inter-connected PRs. #24 #25 #26 #27 #28 

The downside: Maintaining can be a pain. Changing in one PR would result in rebasing all the remaining PRs.

**Pull request closed without merging**
